server:
  port: 8090

wmrpc:
  zk:
    server: localhost:2181
    root: wmrpc-rc
  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0
  consumer:
    retries: 2
    timeout: 1000
    grayRatio: 33
    faultLimit: 10
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000

logging:
  level:
    root: error
    cn.william.wmrpc: debug