server:
  port: 8081

wmrpc:
  zk:
    server: localhost:2181
    root: wmrpc-rc
  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001

logging:
  level:
    root: error
    cn.william.wmrpc: debug