server:
  port: 8081

wmrpc:
  zk:
    server: localhost:2181
    root: wmrpc-rc
  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tpsLimit: 5

zwregistry:
  server: http://localhost:8484

app:
  id: main-app

apollo:
  cacheDir: /Users/zhangwei/Downloads/programs/apollo-quick-start-2.2.0/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: app1
    eagerLoad:
      enabled: false

logging:
  level:
    root: error
    cn.william.wmrpc: debug
    cn.kimmking: debug
    io.github.zhangwei1989: debug
