### 获取8090用户信息
GET http://localhost:8090/?id=1000

### 获取8090调用超时信息
GET http://localhost:8090/find/?timeout=1500

### 调整8090灰度比例
GET http://localhost:8090/gray?ratio=100

### 获取provider 8081端接口调整 ports
GET http://localhost:8081/ports?ports=8082

### 获取provider 8082端接口调整 ports
GET http://localhost:8082/ports?ports=8082

### 获取provider 8081端配置参数 metas
GET http://localhost:8081/meta

### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service" : "cn.william.wmrpc.demo.api.UserService",
  "method" : "findById",
  "args" : [100]
}

### 获取订单信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service" : "cn.william.wmrpc.demo.api.OrderService",
  "method" : "findById",
  "args" : [200]
}
