### 获取8088用户信息
GET http://localhost:8088/?id=101

### 获取8088调用超时接口
GET http://localhost:8088/find/?timeout=1500

### 获取8088调用修改超
GET http://localhost:8082/ports?ports=8081

### 获取用户信息
POST http://localhost:8082/
Content-Type: application/json

{
  "service" : "cn.william.wmrpc.demo.api.UserService",
  "methodSign" : "findById@1_int",
  "args" : [100]
}

### 获取订单信息
POST http://localhost:8081/
Content-Type: application/json

{
  "service" : "cn.william.wmrpc.demo.api.OrderService",
  "methodSign" : "findById",
  "args" : [200]
}

### mock
POST http://localhost:8081/
Content-Type: application/json

{
  "service" : "cn.william.wmrpc.demo.api.UserService",
  "methodSign" : "findById@2_int_java.lang.String",
  "args" : [100, "CC"]
}

