server:
  port: 8091

wmrpc:
  zk:
    server: localhost:2181
    root: wmrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    timeout: 1000
    grayRatio: 33
    faultLimit: 10
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000

zwregistry:
  servers: http://localhost:8484

app:
  id: app2

apollo:
  cacheDir: /Users/zhangwei/Downloads/programs/apollo-quick-start-2.2.0/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: app2
    eagerLoad:
      enabled: false

logging:
  level:
    root: error
    cn.william.wmrpc: debug